### ISSUE TITLE
留言 - Yoowin's Blog

### ISSUE THREAD

**Issue by yoowinsu** [yoowinsu/yoowinsu.github.io#1]
https://yoowin.me/message/

**Comment by yoowinsu** [comment]
评论系统从来必力换成了gitment，试试效果先

* 还支持markdown，厉害了
* 还支持图片、列表
* 来必力很坑很坑...

| 列1 | 列2 | 列3 |
| ---| --- | --- |
| 1 | 2 | 3 |
| hei | ha | ha |

[我的博客yoowin.me](https://yoowin.me)
![](https://avatars3.githubusercontent.com/u/20217398?v=4&s=40)

**Comment by yoowinsu** [comment]
评论系统从来必力换成了gitment，试试效果先

* 支持markdown，厉害了
* 可以自定义样式
* [yoowin.me](https://yoowin.me)

**Comment by yoowinsu** [comment]
sdasd

**Comment by yoowinsu** [comment]
ssd

**Comment by yoowinsu** [comment]
xxz

**Comment by yoowinsu** [comment]
**sass**
xzx

**Comment by yoowinsu** [comment]
dafdas

**Comment by yoowinsu** [comment]
评论下

**Comment by yoowinsu** [comment]
dsdafffff



fdgdfgdfg
```js
let a = ddd
```


dsfdsfczxvt

**Comment by yoowinsu** [comment]
天际蓝开口跪

**Comment by yoowinsu** [comment]
@yoowinsu gffjjgfghh

**Comment by yoowinsu** [comment]
- 一
- 二
- 三

**Comment by yoowinsu** [comment]
```js
for(let i=0;i<10;i++){
  setTimeout(function(){
	alert(i)
  },0)
}
```

**Comment by yoowinsu** [comment]
```js
function double(arr){
  for(i=arr.length-1;i>=0;i--){
    arr.splice(i,0,arr[i])
  }
  return arr
}
double([9,6,3,88,777]) //[9, 9, 6, 6, 3, 3, 88, 88, 777, 777]

```

**Comment by yoowinsu** [comment]
```html
<style>
  .wrap{
  margin: 0 auto;
  height: 300px;
  background-color: #ccc;
}
.first{
  background-color: pink;
}
.second{
  background-color: #777;
}
</style>
<body>
  <div class="wrap">
    <div class="first"></div>
    <div class="second"></div>
  </div>
</body>
```

**Comment by yoowinsu** [comment]
```css

/*水平垂直居中一*/
/*确定容器的宽高 宽500 高 300 的层*/
/*设置层的外边距*/
 div {
 	position: relative;		/* 相对定位或绝对定位均可 */
 	width:500px;
 	height:300px;
 	top: 50%;
 	left: 50%;
 	margin: -150px 0 0 -250px;     	/* 外边距为自身宽高的一半 */
 	background-color: pink;	 	/* 方便看效果 */
  }
/*水平垂直居中二*/
/*未知容器的宽高，利用 `transform` 属性*/
 div {
 	position: absolute;		/* 相对定位或绝对定位均可 */
 	top: 50%;
 	left: 50%;
 	transform: translate(-50%, -50%);
 	background-color: pink;	 	/* 方便看效果 */
 }
/*水平垂直居中三*/
/* 利用 flex 布局*/
/* 实际使用时应考虑兼容性*/
 .container {
 	display: flex;
 	align-items: center; 		/* 垂直居中 */
 	justify-content: center;	/* 水平居中 */
 }
 .container div {
 	width: 100px;
 	height: 100px;
 	background-color: pink;		/* 方便看效果 */
 }
```
